<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Intelligence.TradeSystem.ServiceDefaults\Intelligence.TradeSystem.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Intelligence.TradeSystem.Bff.Tests" />
  </ItemGroup>

</Project>
