<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Intelligence.TradeSystem.Analytics\Intelligence.TradeSystem.Analytics.csproj" />
    <ProjectReference Include="..\Intelligence.TradeSystem.Domain\Intelligence.TradeSystem.Domain.csproj" />
  </ItemGroup>

</Project>
