<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Intelligence.TradeSystem.Infrastructure" />
    <InternalsVisibleTo Include="Intelligence.TradeSystem.Domain.Tests" />
    <InternalsVisibleTo Include="Intelligence.TradeSystem.Infrastructure.IntegrationTests" />
  </ItemGroup>

</Project>
