// <auto-generated />
using System;
using Intelligence.TradeSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Intelligence.TradeSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradeSystemDbContext))]
    [Migration("20260904132342_InitialDomainPersistence")]
    partial class InitialDomainPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.ExchangeAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("exchange_account_id");

                    b.Property<int>("Capabilities")
                        .HasColumnType("integer")
                        .HasColumnName("capabilities");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("connection_status");

                    b.Property<string>("ExchangeId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("exchange_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("exchange_accounts", (string)null);
                });

            modelBuilder.Entity("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PortfolioPositionStateEntity", b =>
                {
                    b.Property<long>("PortfolioStateId")
                        .HasColumnType("bigint")
                        .HasColumnName("portfolio_state_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<decimal?>("AverageEntryPrice")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("average_entry_price");

                    b.Property<Guid>("ExchangeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("exchange_account_id");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("instrument_id");

                    b.Property<DateTimeOffset>("LastObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_observed_at");

                    b.Property<decimal?>("Leverage")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("leverage");

                    b.Property<decimal?>("LiquidationPrice")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("liquidation_price");

                    b.Property<decimal?>("MarkPrice")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("mark_price");

                    b.Property<string>("MarketCategory")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("market_category");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<int>("PositionIdx")
                        .HasColumnType("integer")
                        .HasColumnName("position_idx");

                    b.Property<string>("PositionSide")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("position_side");

                    b.Property<decimal?>("PositionValue")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("position_value");

                    b.Property<decimal>("Size")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("size");

                    b.Property<string>("TrackingState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tracking_state");

                    b.Property<decimal?>("UnrealizedPnl")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("unrealized_pnl");

                    b.HasKey("PortfolioStateId", "Sequence");

                    b.HasIndex("ExchangeAccountId");

                    b.HasIndex("PositionId");

                    b.ToTable("portfolio_position_states", null, t =>
                        {
                            t.HasCheckConstraint("ck_portfolio_position_states_sequence_positive", "sequence > 0");
                        });
                });

            modelBuilder.Entity("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PortfolioStateEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("portfolio_state_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AvailableCapital")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("available_capital");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<DateTimeOffset?>("CapitalObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("capital_observed_at");

                    b.Property<Guid>("ExchangeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("exchange_account_id");

                    b.Property<decimal?>("FreeCapital")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("free_capital");

                    b.Property<decimal?>("FreeCapitalPercent")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("free_capital_percent");

                    b.Property<decimal?>("GrossExposure")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("gross_exposure");

                    b.Property<decimal?>("GrossExposureToEquityPercent")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("gross_exposure_to_equity_percent");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complete");

                    b.Property<bool>("IsFresh")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fresh");

                    b.Property<decimal?>("LargestPositionConcentrationPercent")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("largest_position_concentration_percent");

                    b.Property<Guid?>("LargestPositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("largest_position_id");

                    b.Property<decimal?>("LongExposure")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("long_exposure");

                    b.Property<decimal?>("NetExposure")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("net_exposure");

                    b.Property<decimal?>("ShortExposure")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("short_exposure");

                    b.Property<TimeSpan>("StaleAfter")
                        .HasColumnType("interval")
                        .HasColumnName("stale_after");

                    b.Property<decimal?>("TotalEquity")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("total_equity");

                    b.Property<decimal?>("TotalUnrealizedPnl")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("total_unrealized_pnl");

                    b.Property<decimal?>("TotalWalletBalance")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("total_wallet_balance");

                    b.Property<decimal?>("UsedCapital")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("used_capital");

                    b.HasKey("Id");

                    b.HasIndex("LargestPositionId");

                    b.HasIndex("ExchangeAccountId", "CalculatedAt", "Id")
                        .HasDatabaseName("ix_portfolio_states_account_calculated_at");

                    b.ToTable("portfolio_states", (string)null);
                });

            modelBuilder.Entity("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PositionAssessmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("position_assessment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExchangeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("exchange_account_id");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("instrument_id");

                    b.Property<DateTimeOffset>("MarketCapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("market_captured_at");

                    b.Property<DateTimeOffset>("PortfolioCalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("portfolio_calculated_at");

                    b.Property<string>("PortfolioRiskDecision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("portfolio_risk_decision");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<DateTimeOffset>("PositionObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("position_observed_at");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("rule_version");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeAccountId");

                    b.HasIndex("PositionId");

                    b.ToTable("position_assessments", (string)null);
                });

            modelBuilder.Entity("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PositionAssessmentReasonEntity", b =>
                {
                    b.Property<Guid>("PositionAssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_assessment_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason_code");

                    b.HasKey("PositionAssessmentId", "Sequence");

                    b.HasIndex("PositionAssessmentId", "ReasonCode")
                        .IsUnique()
                        .HasDatabaseName("ux_position_assessment_reasons_code");

                    b.ToTable("position_assessment_reasons", (string)null);
                });

            modelBuilder.Entity("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PositionChangeEntity", b =>
                {
                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<decimal?>("AfterAverageEntryPrice")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("after_average_entry_price");

                    b.Property<decimal?>("AfterBreakEvenPrice")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("after_break_even_price");

                    b.Property<decimal?>("AfterLeverage")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("after_leverage");

                    b.Property<decimal?>("AfterLiquidationPrice")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("after_liquidation_price");

                    b.Property<decimal?>("AfterMarkPrice")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("after_mark_price");

                    b.Property<decimal?>("AfterPositionValue")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("after_position_value");

                    b.Property<decimal>("AfterSize")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("after_size");

                    b.Property<decimal?>("AfterStopLoss")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("after_stop_loss");

                    b.Property<decimal?>("AfterTakeProfit")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("after_take_profit");

                    b.Property<decimal?>("AfterTrailingStop")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("after_trailing_stop");

                    b.Property<decimal?>("AfterUnrealizedPnl")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("after_unrealized_pnl");

                    b.Property<decimal?>("BeforeAverageEntryPrice")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("before_average_entry_price");

                    b.Property<decimal?>("BeforeBreakEvenPrice")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("before_break_even_price");

                    b.Property<decimal?>("BeforeLeverage")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("before_leverage");

                    b.Property<decimal?>("BeforeLiquidationPrice")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("before_liquidation_price");

                    b.Property<decimal?>("BeforeMarkPrice")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("before_mark_price");

                    b.Property<decimal?>("BeforePositionValue")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("before_position_value");

                    b.Property<decimal?>("BeforeSize")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("before_size");

                    b.Property<decimal?>("BeforeStopLoss")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("before_stop_loss");

                    b.Property<decimal?>("BeforeTakeProfit")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("before_take_profit");

                    b.Property<decimal?>("BeforeTrailingStop")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("before_trailing_stop");

                    b.Property<decimal?>("BeforeUnrealizedPnl")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("before_unrealized_pnl");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cause");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("TrackingStateAfter")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tracking_state_after");

                    b.HasKey("PositionId", "Sequence");

                    b.ToTable("position_changes", null, t =>
                        {
                            t.HasCheckConstraint("ck_position_changes_sequence_positive", "sequence > 0");
                        });
                });

            modelBuilder.Entity("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PositionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<decimal?>("AverageEntryPrice")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("average_entry_price");

                    b.Property<decimal?>("BreakEvenPrice")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("break_even_price");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid>("ExchangeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("exchange_account_id");

                    b.Property<DateTimeOffset>("FirstDetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_detected_at");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("instrument_id");

                    b.Property<DateTimeOffset>("LastObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_observed_at");

                    b.Property<decimal?>("Leverage")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("leverage");

                    b.Property<decimal?>("LiquidationPrice")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("liquidation_price");

                    b.Property<decimal?>("MarkPrice")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("mark_price");

                    b.Property<string>("MarketCategory")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("market_category");

                    b.Property<int>("PositionIdx")
                        .HasColumnType("integer")
                        .HasColumnName("position_idx");

                    b.Property<string>("PositionSide")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("position_side");

                    b.Property<decimal?>("PositionValue")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("position_value");

                    b.Property<decimal>("Size")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("size");

                    b.Property<decimal?>("StopLoss")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("stop_loss");

                    b.Property<decimal?>("TakeProfit")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("take_profit");

                    b.Property<string>("TrackingState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tracking_state");

                    b.Property<decimal?>("TrailingStop")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("trailing_stop");

                    b.Property<decimal?>("UnrealizedPnl")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("unrealized_pnl");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeAccountId", "InstrumentId", "PositionSide", "PositionIdx")
                        .IsUnique()
                        .HasDatabaseName("ux_positions_active_exchange_key")
                        .HasFilter("\"tracking_state\" <> 'Closed'");

                    b.ToTable("positions", null, t =>
                        {
                            t.HasCheckConstraint("ck_positions_position_idx_non_negative", "position_idx >= 0");
                        });
                });

            modelBuilder.Entity("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.RecommendationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("AddDecision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("add_decision");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_assessment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DismissedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dismissed_at");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("policy_version");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("recommended_action");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SupersededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("superseded_at");

                    b.Property<Guid?>("SupersededByRecommendationId")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by_recommendation_id");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("PositionId");

                    b.HasIndex("SupersededByRecommendationId");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.RecommendationReasonEntity", b =>
                {
                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason_code");

                    b.HasKey("RecommendationId", "Sequence");

                    b.HasIndex("RecommendationId", "ReasonCode")
                        .IsUnique()
                        .HasDatabaseName("ux_recommendation_reasons_code");

                    b.ToTable("recommendation_reasons", (string)null);
                });

            modelBuilder.Entity("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PortfolioPositionStateEntity", b =>
                {
                    b.HasOne("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.ExchangeAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("ExchangeAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_position_states_exchange_accounts");

                    b.HasOne("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PortfolioStateEntity", null)
                        .WithMany("Positions")
                        .HasForeignKey("PortfolioStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_position_states_portfolio_states");

                    b.HasOne("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PositionEntity", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_position_states_positions");
                });

            modelBuilder.Entity("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PortfolioStateEntity", b =>
                {
                    b.HasOne("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.ExchangeAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("ExchangeAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_states_exchange_accounts");

                    b.HasOne("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PositionEntity", null)
                        .WithMany()
                        .HasForeignKey("LargestPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_portfolio_states_largest_position");
                });

            modelBuilder.Entity("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PositionAssessmentEntity", b =>
                {
                    b.HasOne("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.ExchangeAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("ExchangeAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_position_assessments_exchange_accounts");

                    b.HasOne("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PositionEntity", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_position_assessments_positions");
                });

            modelBuilder.Entity("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PositionAssessmentReasonEntity", b =>
                {
                    b.HasOne("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PositionAssessmentEntity", null)
                        .WithMany()
                        .HasForeignKey("PositionAssessmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_position_assessment_reasons_assessments");
                });

            modelBuilder.Entity("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PositionChangeEntity", b =>
                {
                    b.HasOne("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PositionEntity", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_position_changes_positions");
                });

            modelBuilder.Entity("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PositionEntity", b =>
                {
                    b.HasOne("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.ExchangeAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("ExchangeAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_positions_exchange_accounts");
                });

            modelBuilder.Entity("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.RecommendationEntity", b =>
                {
                    b.HasOne("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PositionAssessmentEntity", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recommendations_position_assessments");

                    b.HasOne("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PositionEntity", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recommendations_positions");

                    b.HasOne("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.RecommendationEntity", null)
                        .WithMany()
                        .HasForeignKey("SupersededByRecommendationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recommendations_successor");
                });

            modelBuilder.Entity("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.RecommendationReasonEntity", b =>
                {
                    b.HasOne("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.RecommendationEntity", null)
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recommendation_reasons_recommendations");
                });

            modelBuilder.Entity("Intelligence.TradeSystem.Infrastructure.Persistence.Entities.PortfolioStateEntity", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
